import Head  from 'next/head'
import React from 'react'


export default function Layout({Children} ) {
  return (
   <>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <div className='flex min-h-screen flex-col justify-between'>
       <header>
           Header
       </header>
       <main>{Children}</main>
       <footer>
           Footer
       </footer>
   </div>

   </>
  )
}
